/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ozgecmisproje;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.ButtonGroup;
import javax.swing.JPanel;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author mert
 */
public class NewJFrame extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    public NewJFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jTabbedPane2 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        txtAd = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        txtYil = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        txtYer = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        txtUyruk = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        txtEhliyet = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        txtAskerlik = new javax.swing.JTextField();
        btnKisisel = new javax.swing.JButton();
        radioEvli = new javax.swing.JRadioButton();
        radioBekar = new javax.swing.JRadioButton();
        jPanel4 = new javax.swing.JPanel();
        txtDeneyim = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        txtDeneyimAy = new javax.swing.JTextField();
        btnDeneyim = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        txtOkul = new javax.swing.JTextField();
        cmbLisans = new javax.swing.JComboBox();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btnEgitim = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        txtReferans = new javax.swing.JTextField();
        btnReferans = new javax.swing.JButton();
        jPanel7 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtSertifikaAd = new javax.swing.JTextField();
        txtGecerlilikSuresi = new javax.swing.JTextField();
        btnSertifika = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tableDeneyim = new javax.swing.JTable();
        jScrollPane3 = new javax.swing.JScrollPane();
        tableBilgiler = new javax.swing.JTable();
        jScrollPane4 = new javax.swing.JScrollPane();
        tableSertifika = new javax.swing.JTable();
        jScrollPane5 = new javax.swing.JScrollPane();
        tableEgitim = new javax.swing.JTable();
        jScrollPane6 = new javax.swing.JScrollPane();
        tableReferans = new javax.swing.JTable();
        txt_Ara = new javax.swing.JTextField();
        btn_Ara = new javax.swing.JButton();
        jLabel18 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jLabel9.setText("AD SOYAD:");

        jLabel10.setText("DOGUM YILI:");

        jLabel11.setText("DOGUM YERI:");

        jLabel12.setText("UYRUK:");

        jLabel13.setText("MEDENI DURUM:");

        jLabel14.setText("EHLIYET:");

        jLabel15.setText("ASKERLIK DURUMU:");

        btnKisisel.setText("Kişisel Bilgilerimi Kaydet");
        btnKisisel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKisiselActionPerformed(evt);
            }
        });

        radioEvli.setText("Evli");
        radioEvli.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                radioEvliMouseClicked(evt);
            }
        });

        radioBekar.setText("Bekar");
        radioBekar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                radioBekarMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel9)
                    .addComponent(jLabel10)
                    .addComponent(jLabel11)
                    .addComponent(jLabel12)
                    .addComponent(jLabel13)
                    .addComponent(jLabel14)
                    .addComponent(jLabel15))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(btnKisisel, javax.swing.GroupLayout.DEFAULT_SIZE, 168, Short.MAX_VALUE)
                        .addComponent(txtAskerlik, javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(txtEhliyet, javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(txtYer, javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(txtYil, javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(txtAd)
                        .addComponent(txtUyruk))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(radioEvli)
                        .addGap(34, 34, 34)
                        .addComponent(radioBekar)))
                .addContainerGap(93, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(txtAd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(txtYil, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(txtYer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtUyruk, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(radioEvli)
                    .addComponent(radioBekar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtEhliyet, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtAskerlik, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel15))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnKisisel)
                .addContainerGap(85, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jTabbedPane2.addTab("Kişisel Bilgiler", jPanel2);

        jLabel16.setText("DENEYİM ADI:");

        jLabel17.setText("ÇALIŞMA SÜRESİ(AY):");

        btnDeneyim.setText("Deneyim Kaydet");
        btnDeneyim.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeneyimActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel17)
                    .addComponent(jLabel16))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtDeneyimAy)
                    .addComponent(txtDeneyim)
                    .addComponent(btnDeneyim, javax.swing.GroupLayout.DEFAULT_SIZE, 115, Short.MAX_VALUE))
                .addContainerGap(127, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(txtDeneyim, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(txtDeneyimAy, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnDeneyim)
                .addContainerGap(198, Short.MAX_VALUE))
        );

        jTabbedPane2.addTab("Deneyimler", jPanel4);

        cmbLisans.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Ön Lisans", "Lisans", "Yüksek Lisans", "Açık Öğretim", "Doktora" }));

        jLabel1.setText("Okul Adı:");

        jLabel2.setText("Lisans Derecesi:");

        btnEgitim.setText("Eğitim Kaydet");
        btnEgitim.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEgitimActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnEgitim, javax.swing.GroupLayout.DEFAULT_SIZE, 155, Short.MAX_VALUE)
                    .addComponent(txtOkul)
                    .addComponent(cmbLisans, 0, 155, Short.MAX_VALUE))
                .addContainerGap(104, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtOkul, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmbLisans, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addComponent(btnEgitim)
                .addContainerGap(201, Short.MAX_VALUE))
        );

        jTabbedPane2.addTab("Eğitim", jPanel5);

        jLabel3.setText("Referans Adı:");

        btnReferans.setText("Referans Kaydet");
        btnReferans.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReferansActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(80, 80, 80)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnReferans, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtReferans))
                .addContainerGap(135, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtReferans, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnReferans)
                .addContainerGap(241, Short.MAX_VALUE))
        );

        jTabbedPane2.addTab("Referanslar", jPanel6);

        jLabel4.setText("Sertifika Adı:");

        jLabel5.setText("Geçerlilik Süresi:");

        btnSertifika.setText("Sertifika Kaydet");
        btnSertifika.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSertifikaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(72, 72, 72)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel5)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtSertifikaAd)
                    .addComponent(txtGecerlilikSuresi, javax.swing.GroupLayout.DEFAULT_SIZE, 117, Short.MAX_VALUE)
                    .addComponent(btnSertifika, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(128, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtSertifikaAd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtGecerlilikSuresi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnSertifika)
                .addContainerGap(200, Short.MAX_VALUE))
        );

        jTabbedPane2.addTab("Sertifikalar", jPanel7);

        jTabbedPane1.addTab("Özgeçmiş Yarat", jTabbedPane2);

        tableDeneyim.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(tableDeneyim);

        tableBilgiler.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane3.setViewportView(tableBilgiler);

        tableSertifika.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane4.setViewportView(tableSertifika);

        tableEgitim.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane5.setViewportView(tableEgitim);

        tableReferans.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane6.setViewportView(tableReferans);

        btn_Ara.setText("Ara");
        btn_Ara.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_AraActionPerformed(evt);
            }
        });

        jLabel18.setText("Ad Soyad Ara:");

        jLabel6.setText("Kişisel Bilgiler;");

        jLabel7.setText("Deneyimler;");

        jLabel8.setText("Eğitimler;");

        jLabel19.setText("Referanslar;");

        jLabel20.setText("Sertifikalar;");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 372, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 372, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 372, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 372, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addComponent(jLabel18)
                        .addGap(13, 13, 13)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btn_Ara, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txt_Ara, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel6))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel7))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel8))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 372, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel19))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel20)))
                .addContainerGap(603, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18)
                    .addComponent(txt_Ara, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_Ara)
                .addGap(13, 13, 13)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(2, 2, 2)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(2, 2, 2)
                .addComponent(jLabel8)
                .addGap(3, 3, 3)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel19)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel20)
                .addGap(7, 7, 7)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(71, Short.MAX_VALUE))
        );

        jScrollPane1.setViewportView(jPanel1);

        jTabbedPane1.addTab("Özgeçmiş Ara", jScrollPane1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 414, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 387, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void RadioGrupla() {
        ButtonGroup medeni = new ButtonGroup();
        medeni.add(radioEvli);
        medeni.add(radioBekar);
    }
    Baglanti baglan = new Baglanti();
    int durum = 0;
    private JPanel contentPane;
    private JTable table;
    DefaultTableModel modelBilgiler = new DefaultTableModel();
    Object[] kolonBilgiler = {"AD", "DOĞUM YILI", "DOĞUM YERİ", "UYRUK", "MEDENİ DURUM", "EHLİYET", "ASKERLİK DURUMU"};
    Object[] kolonSatirlar = new Object[7];

    DefaultTableModel modelDeneyim = new DefaultTableModel();
    Object[] kolonDeneyim = {"DENEYİM", "DENEYİM SÜRESİ"};
    Object[] deneyimSatirlar = new Object[2];

    DefaultTableModel modelEgitim = new DefaultTableModel();
    Object[] kolonEgitim = {"OKUL ADI", "LİSANS DERECESİ"};
    Object[] egitimSatirlar = new Object[2];

    DefaultTableModel modelReferans = new DefaultTableModel();
    Object[] kolonReferans = {"REFERANS"};
    Object[] referansSatirlar = new Object[1];

    DefaultTableModel modelSertifika = new DefaultTableModel();
    Object[] kolonSertifika = {"SERTİFİKA ADI", "GEÇERLİLİK SÜRESİ"};
    Object[] sertifikaSatirlar = new Object[2];
    private void btnKisiselActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKisiselActionPerformed
        baglan.BilgiEkle(txtAd.getText(), txtYil.getText(), txtYer.getText(), txtUyruk.getText(), durum, txtEhliyet.getText(), txtAskerlik.getText());
        btnKisisel.setVisible(false);
    }//GEN-LAST:event_btnKisiselActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        RadioGrupla();
    }//GEN-LAST:event_formWindowOpened

    private void radioEvliMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_radioEvliMouseClicked
        durum = 1;
    }//GEN-LAST:event_radioEvliMouseClicked

    private void radioBekarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_radioBekarMouseClicked
        durum = 0;
    }//GEN-LAST:event_radioBekarMouseClicked

    private void btnDeneyimActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeneyimActionPerformed
        baglan.DeneyimEkle(txtDeneyim.getText(), Integer.parseInt(txtDeneyimAy.getText()));
    }//GEN-LAST:event_btnDeneyimActionPerformed

    private void btnEgitimActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEgitimActionPerformed
        String dondur = "";
        if (cmbLisans.getSelectedIndex() == 0) {
            dondur = "Ön Lisans";
        } else if (cmbLisans.getSelectedIndex() == 1) {
            dondur = "Lisans";
        } else if (cmbLisans.getSelectedIndex() == 2) {
            dondur = "Yüksek Lisans";
        } else if (cmbLisans.getSelectedIndex() == 3) {
            dondur = "Açık Öğretim";
        } else if (cmbLisans.getSelectedIndex() == 4) {
            dondur = "Doktora";
        }
        baglan.EgitimEkle(txtOkul.getText(), dondur);
    }//GEN-LAST:event_btnEgitimActionPerformed

    private void btnReferansActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReferansActionPerformed
        baglan.ReferansEkle(txtReferans.getText());
    }//GEN-LAST:event_btnReferansActionPerformed

    private void btnSertifikaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSertifikaActionPerformed
        baglan.SertifikaEkle(txtSertifikaAd.getText(), Integer.parseInt(txtGecerlilikSuresi.getText()));
    }//GEN-LAST:event_btnSertifikaActionPerformed

    private void btn_AraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_AraActionPerformed
        String gelen = txt_Ara.getText();
        
        try {
            modelBilgiler.setRowCount(0);
            int gelenID = 0;
            Connection con = DriverManager.getConnection("jdbc:derby://localhost:1527/db_Ozgecmis", "sa", "as");
            //Bilgiler
            String query = "select * from TBL_BILGILER where AD LIKE ?";
            PreparedStatement ps = con.prepareStatement(query);
            ps.setString(1, "%" + gelen + "%");
            ResultSet rs = ps.executeQuery();
            tableBilgiler.setModel(modelBilgiler);
            modelBilgiler.setColumnIdentifiers(kolonBilgiler);
            while (rs.next()) {
                gelenID = rs.getInt("ID");
                kolonSatirlar[0] = rs.getString("AD");
                kolonSatirlar[1] = rs.getString("YIL");
                kolonSatirlar[2] = rs.getString("YER");
                kolonSatirlar[3] = rs.getString("UYRUK");
                kolonSatirlar[4] = rs.getString("MEDENIDURUM");
                kolonSatirlar[5] = rs.getString("EHLIYET");
                kolonSatirlar[6] = rs.getString("ASKERLIK");
                modelBilgiler.addRow(kolonSatirlar);
            }
            System.out.println("Bilgiler Tablosu Eklendi...");
            //Deneyim
            String queryDeneyim = "select * from TBL_DENEYIM where kisiid="+gelenID;
            PreparedStatement psD = con.prepareStatement(queryDeneyim);
            ResultSet rsD = psD.executeQuery();
            tableDeneyim.setModel(modelDeneyim);
            modelDeneyim.setColumnIdentifiers(kolonDeneyim);
            while (rsD.next()) {
                deneyimSatirlar[0] = rsD.getString("DENEYIMADI");
                deneyimSatirlar[1] = rsD.getString("SURE");
                modelDeneyim.addRow(deneyimSatirlar);
            }
            System.out.println("Deneyim Tablosu Eklendi...");
            //Eğitim
            String queryEgitim = "select * from TBL_EGITIM where kisiid="+gelenID;
            PreparedStatement psE = con.prepareStatement(queryEgitim);
            ResultSet rsE = psE.executeQuery();
            tableEgitim.setModel(modelEgitim);
            modelEgitim.setColumnIdentifiers(kolonEgitim);
            while (rsE.next()) {
                egitimSatirlar[0] = rsE.getString("OKULADI");
                egitimSatirlar[1] = rsE.getString("LISANSDERECE");
                modelEgitim.addRow(egitimSatirlar);
            }
            System.out.println("Eğitim Tablosu Eklendi...");
            //Referans
            String queryReferans = "select * from TBL_REFERANS where kisiid="+gelenID;
            PreparedStatement psR = con.prepareStatement(queryReferans);
            ResultSet rsR = psR.executeQuery();
            tableReferans.setModel(modelReferans);
            modelReferans.setColumnIdentifiers(kolonReferans);
            while (rsR.next()) {
                referansSatirlar[0] = rsR.getString("REFERANSAD");
                modelReferans.addRow(referansSatirlar);
            }
            System.out.println("Referans Tablosu Eklendi...");
            //Sertifika
            String querySertifika = "select * from TBL_SERTIFIKA where kisiid="+gelenID;
            PreparedStatement psS = con.prepareStatement(querySertifika);
            ResultSet rsS = psS.executeQuery();
            tableSertifika.setModel(modelSertifika);
            modelSertifika.setColumnIdentifiers(kolonSertifika);
            while (rsS.next()) {
                sertifikaSatirlar[0] = rsS.getString("SERTIKIFAAD");
                sertifikaSatirlar[1] = rsS.getString("GECERLILIK");
                modelSertifika.addRow(sertifikaSatirlar);
            }
            System.out.println("Sertifika Tablosu Eklendi...");
        } catch (Exception e) {
            System.out.println("Tablo Eklemede Bir Hata Oluştu...   " + e);
        }
    }//GEN-LAST:event_btn_AraActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDeneyim;
    private javax.swing.JButton btnEgitim;
    private javax.swing.JButton btnKisisel;
    private javax.swing.JButton btnReferans;
    private javax.swing.JButton btnSertifika;
    private javax.swing.JButton btn_Ara;
    private javax.swing.JComboBox cmbLisans;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTabbedPane jTabbedPane2;
    private javax.swing.JRadioButton radioBekar;
    private javax.swing.JRadioButton radioEvli;
    private javax.swing.JTable tableBilgiler;
    private javax.swing.JTable tableDeneyim;
    private javax.swing.JTable tableEgitim;
    private javax.swing.JTable tableReferans;
    private javax.swing.JTable tableSertifika;
    private javax.swing.JTextField txtAd;
    private javax.swing.JTextField txtAskerlik;
    private javax.swing.JTextField txtDeneyim;
    private javax.swing.JTextField txtDeneyimAy;
    private javax.swing.JTextField txtEhliyet;
    private javax.swing.JTextField txtGecerlilikSuresi;
    private javax.swing.JTextField txtOkul;
    private javax.swing.JTextField txtReferans;
    private javax.swing.JTextField txtSertifikaAd;
    private javax.swing.JTextField txtUyruk;
    private javax.swing.JTextField txtYer;
    private javax.swing.JTextField txtYil;
    private javax.swing.JTextField txt_Ara;
    // End of variables declaration//GEN-END:variables
}
